version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: container_akasha_admin
    ports:
      - "5037:80"
    volumes:
      - ./dist/admin:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf  # Montar el archivo de configuraci√≥n
    restart: always
    networks:
      - red_akasha

networks:
  red_akasha:
    driver: bridge
